name: Twitter Cron

on:
  schedule:
    - cron: '30 5 * * *'  
    - cron: '0 14 * * *' 
    - cron: '0 20 * * *'  

jobs:
  tweet:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '14'

      - name: Install dependencies
        run: npm install

      - name: Run Twitter Bot
        run: node index.js  
        env:
          API_KEY: ${{ secrets.API_KEY }}
          API_SECRET: ${{ secrets.API_SECRET }}
          ACCESS_TOKEN: ${{ secrets.ACCESS_TOKEN }}
          ACCESS_SECRET: ${{ secrets.ACCESS_SECRET }}
          BEARER_TOKEN: ${{ secrets.BEARER_TOKEN }}
          APP_ID: ${{ secrets.APP_ID }}
          GOOGLE_API_KEY: ${{ secrets.GOOGLE_API_KEY }}
